version: '3.8'

networks:
  red_mpd:   # red interna compartida
    name: red_mpd

services:

  s_pgsqlmpd:
    image: postgres
    container_name: c_pgsqlmpd
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - ${VOLUME_PGSQL}:/var/lib/postgresql/data # Persistencia de datos
    networks:
      - red_mpd

  s_pgadmin:
    image: dpage/pgadmin4
    container_name: c_pgadminazu
    environment:
      PGADMIN_DEFAULT_EMAIL: "sergio.salinasr@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "86:80"
    volumes:
      - ${VOLUME_PGADMIN}:/var/lib/pgadmin
    depends_on:
      - s_pgsqlmpd
    networks:
      - red_mpd

  s_keycloakmpd:
    image: quay.io/keycloak/keycloak:12.0.2
    container_name: c_keycloakmpdazu
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ${VOLUME_KEYCLOAK_DATA}:/opt/jboss/keycloak/standalone/data
      - ${VOLUME_KEYCLOAK_LOGS}:/opt/jboss/keycloak/standalone/log
    networks:
      - red_mpd


# docker compose --env-file .env -f docker/dc_basempdazu.yaml -p dc_basempdazu up -d
# EN LA CREACIÓN DEL SERVER EN PGADMIN, LA PRIMERA VEZ
# considerar el nombre del host como (contenedor) en este caso: c_pgsqlmpd