version: '3.8'

services:
  s_angularmpd:
    image: i_angmpdazu # Asegúrate de que esta imagen ya esté construida y disponible localmente o en un registro accesible
    container_name: c_nginx-angmpd2
    ports:
      - "4200:80"
    environment:
      production: false
      appVersion: '1.1.0'
      env_version: 'v1.0.0'
      env_empresa_logo: "assets/azurian_logo.jpg"
      env_empresa_url: "azurian.com"
      env_nombre_sistema: "Nombre Sistema"
      env_empresa: "Azurian Consulting"
      env_url_backend: http://s_nodeapp:3000
      env_tdu_pais: 1
      env_tdu_sancion: 2
      env_tdu_nivelgravedad: 3
      env_tdu_probabilidad: 4
      env_tdu_impacto: 5
      env_tdu_mitigacion: 6

  s_nodeapp:
    image: i_nodempdazu # Imagen de tu aplicación Node.js
    container_name: c_nodempd
    build:
      context: .
      dockerfile: src/docker/Dockerfile # Ruta al Dockerfile de tu aplicación
    ports:
      - "3000:3000"
    environment:
      DB_USER: root
      DB_HOST: s_pgsqlmpd # Nombre del servicio de PostgreSQL
      DB_PASSWORD: root
      DB_NAME: root
      DB_SCHEMA: mpd
      DB_PORT: 5432
      KEYCLOAK_URL: http://s_keycloakmpd:8080 # Nombre del servicio de Keycloak
      KEYCLOAK_AUTH: http://s_keycloakmpd:8080/auth
    depends_on:
      - s_pgsqlmpd
      - s_keycloakmpd

  s_pgsqlmpd:
    image: postgres
    container_name: c_pgsqlmpd
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - ${VOLUME_PGSQL}:/var/lib/postgresql/data # Persistencia de datos

  s_pgadmin:
    image: dpage/pgadmin4
    container_name: c_pgadminazu
    environment:
      PGADMIN_DEFAULT_EMAIL: "sergio.salinasr@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "85:80"
    volumes:
      - ${VOLUME_PGADMIN}:/var/lib/pgadmin
    depends_on:
      - s_pgsqlmpd

  s_keycloakmpd:
    image: quay.io/keycloak/keycloak:12.0.2
    container_name: c_keycloakmpdazu
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ${VOLUME_KEYCLOAK_DATA}:/opt/jboss/keycloak/standalone/data
      - ${VOLUME_KEYCLOAK_LOGS}:/opt/jboss/keycloak/standalone/log


# docker compose --env-file .env -f docker/dc_fullmpdazu.yaml -p dc_fullmpdazu up -d
# EN LA CREACIÓN DEL SERVER EN PGADMIN, LA PRIMERA VEZ
# considerar el nombre del host como (contenedor) en este caso: c_pgsqlmpd